<HTML>
<HEAD>


<TITLE>Inside Java:Implementing Java Exception Handling:EarthWeb Inc.-</TITLE>






<P><CENTER>
<a href="0387-0391.html">Previous</A> | <a href="..\ewtoc.html">Table of Contents</A> | <a href="0396-0400.html">Next</A>
</CENTER></P>

<A NAME="PAGENUM-392"><P>Page 392</P></A>


<PRE>
// Prints the Throwable and the Throwable's stack trace.
// The trace is printed on the System.err stream.
public void printStackTrace();

// Prints the Throwable and the Throwable's stack trace.
// The trace is printed on the specified print stream.
public void printStackTrace(java.io.PrintStream s);
</PRE>

<P>You could, therefore, use any of the previous methods on the instance of your
new exception class:
</P>
<PRE>
String excepMsg = prob1.getMessage();
String execpPrint = prob1.toString();
System.out.println(prob1); // Uses toString() to print
prob1.printStackTrace();
</PRE>

<H4><A NAME="ch10_ 7">
Throwing an Exception
</A></H4>

<P>Here is an example of how you would use your new exception within a method:
</P>
<PRE>
public void checkValue(String name)
      throws MyNewException
{
      if (name == null)
      {
         throw new MyNewException(&quot;null value!&quot;);

         } // end if

         // Other logic

} // end checkValue
</PRE>

<P>This is a simple method that throws an exception if a null string value is passed to
the method. The exception that is thrown is an instance of an exception class; that is,
an exception object. The following expression calls the constructor for
MyNewException and creates the exception object:
</P>
<PRE>
new MyNewException(&quot;null value!&quot;);
</PRE>

<P>The throw statement throws the exception object to the caller of the method.
</P>

<A NAME="PAGENUM-393"><P>Page 393</P></A>



<P>Another point to note is the use of the throws clause in the method declaration
where the exception is being thrown:
</P>
<PRE>
public void checkValue(String name)
      throws MyNewException;
</PRE>

<P>Because MyNewException was subclassed from Exception, it is a checked exception.
The language rules require that all the checked exceptions thrown in the method must
be declared in the method declaration as a comma-separated list of exception classes:
</P>
<PRE>
(qualifiers returntype method(parameters)
      throws excep1, excep2, excep3
{


} // end method
</PRE>

<P>The preceding method defines a generic method that can throw three exceptions:
</P>
<PRE>
excep1, excep2, excep3
</PRE>

<P>These three exceptions must be defined as exception classes.
</P>

<P>You can throw exceptions that are extensions of the classes defined in the
exception class. This is because you can use classes anywhere that its superclass is
expected. Therefore, it is possible to write the following code:
</P>
<PRE>
public void checkValue(String name)
      throws Exception
{
      if (name == null)
      {
         throw new MyNewException(&quot;null value!&quot;);

      } // end if

      // Other logic

} // end checkValue
</PRE>

<P>When a programmer examines the method declaration, he or she sees the following:
</P>
<PRE>
public void checkValue(String name)
      throws Exception
</PRE>


<A NAME="PAGENUM-394"><P>Page 394</P></A>



<P>This tells the programmer that an object of class Exception is thrown by the method,
but does not tell the programmer the actual name of the subclassed exception. You
are therefore hiding useful information from the programmer because the programmer
does not know which of the subclassed exception classes could be thrown. The following
is even a worse, although legal, abuse of the language:
</P>
<PRE>
public void checkValue(String name)
      throws Object
{
      if (name == null)
      {
         throw new MyNewException(&quot;null value!&quot;);

      } // end if

      // Other logic

} // end checkValue
</PRE>

<P>In this preceding example, the throws clause is devoid of any useful information as to
the nature of the exception that is thrown by the method because it says that the
exception that is thrown is of class Object. The class Object is a placeholder for any Java
object. Recall that all Java classes ultimately are extensions of the root superclass Object.
</P>
<P>
<P>

<CENTER>
<TABLE BGCOLOR="#FFFF99">
<TR><TD><B>
NOTE
</B></TD></TR>
<TR><TD>
<BLOCKQUOTE>
In the throws clause, you should list the actual class of the exception that could
be thrown by the method, and not the name of the superclass of the exception.
</BLOCKQUOTE></TD></TR>
</TABLE></CENTER>
</P>
<P>The standard runtime exceptions in Java include the following: Arithmetic
Exception, NullPointerException, IndexOutOfBoundsException, ArrayStore-
Exception, ClassCastException, IllegalArgumentException, IllegalMonitorState-
Exception, IllegalThreadStateException, NegativeArraySizeException,
NumberFormat Exception, SecurityException. These exceptions are extensions of
the class RuntimeException and can occur anywhere in the program, and therefore
do not have to be declared in the throws clause.
</P>

<P>Extensions of the Error class also do not have to be declared in the
throws
clause. Error classes indicate more serious errors and include the following
predefined error classes: AbstractMethodError, ClassFormatError,
LinkageError, IllegalAccesError, IncompatibleClassChangeError, InstantiationError, Internal-
Error, UnknownError, NoClassDefFoundError, NoSuchFieldError,
NoSuchMethod-Error, OutOfMemoryError, StackOverflowError, ThreadDeath, UnsatisfiedLinkError,
VerifyError, 
</P>

<A NAME="PAGENUM-395"><P>Page 395</P></A>



<P>VirtualMachineError. An Error class signals a non-recoverable error, so there is no
sense in attempting to catch it. It usually results in an error message being displayed.
The ThreadDeath exception is an exception to this rule, and will not generate an
error message. It causes the thread in which it is thrown to terminate.
</P>

<P>An exception can be thrown inside the body of any method, including a constructor.
A checked exception, however, cannot be thrown in initializers and static initialization
code. The reason for this is that this type of code is executed during object construction,
and there is no user code that can catch these exceptions.
</P>

<H4><A NAME="ch10_ 8">
Catching an Exception
</A></H4>

<P>When a checked exception is thrown, it should be caught. The catching of the
exception is done by using the catch statement:
</P>
<PRE>
try
      trystatement
catch(exception_class identifier)
      block
catch(exception_class identifier)
      block
    .....
finally
      block
</PRE>

<P>First, the try <I>trystatement</I> is executed, and if no exception is encountered in the
execution of this statement, the finally block statement is executed, after which execution
continues with the code after the try-statement The
<I>trystatement</I> can be any Java statement including a block statement.
</P>

<P>
If an exception is encountered in the execution of the
<I>trystatement</I>, further execution of any statements in the
<I>trystatement</I> is halted, and control is transferred to the first
catch clause. If the thrown exception is an instance of the class
<I>exception_class</I>, the <I>identifier</I> value is set to the exception object that was thrown, and the corresponding
block statement is executed. If there is no match with the
<I>exception_class</I>, the catch clauses are tried in the order in which they were listed. At the end, the finally block is
executed. The finally block is always executed last, regardless of whether an exception was
thrown or not. Even if a break statement or return statement is used to exit the
try statement, the finally block is always executed.
</P>

<P>If there is no match with the catch clause of the
try statement, the exception exits the try statement into an outer try statement that may be enclosing this
try statement. This continues until there is a match with a
catch clause. There can be any number of catch clauses in a
try statement, including none. If there is no match with a catch clause in
the
</P>
<P><CENTER>
<a href="0387-0391.html">Previous</A> | <a href="..\ewtoc.html">Table of Contents</A> | <a href="0396-0400.html">Next</A>
</CENTER></P>







</BODY>
</HTML>

